name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::699475942539:role/github-actions-urpdrum-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "urpdrum-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "urpdrum-sa-east-1-terraform-lock"